repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: pretty-format-json
    -   id: check-json
    -   id: requirements-txt-fixer

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
    -   id: autopep8

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    -   id: reorder-python-imports

-   repo: https://github.com/mattlqx/pre-commit-search-and-replace
    rev: v1.0.5
    hooks:
    -   id: search-and-replace
