version: '3'
services:

  caddy:
    image: caddy:2.7.4
    container_name: caddy
    ports:
      - 3000:80
      - 8019:2019
    volumes:
      - ./infra/caddy/Caddyfile:/etc/caddy/Caddyfile
    links:
      - webapp:webapp
    restart: always

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana
    ports:
      - 8020:3000
    links:
      - prometheus:prometheus
    restart: always

  webapp:
      image: marcorfilacarreras/padelquest
      container_name: web
      volumes:
        - /opt/docker/padelquest-grafana:/var/lib/grafana
      links:
        - db:db
      restart: always

  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: padelquest
      MYSQL_DATABASE: padelquest
      MYSQL_USER: padelquest
      MYSQL_PASSWORD: padelquest
    volumes:
      - /opt/docker/padelquest-db:/var/lib/mysql
      - /opt/docker/padelquest-db-conf:/etc/mysql/conf.d
    restart: always
    
  # INSTRUCTIONS:
  #  - mysql -h 127.0.0.1 -P 3306 -u root -p
  #  - GRANT ALL ON padelquest.* to 'padelquest'@'%' IDENTIFIED BY 'padelquest' WITH GRANT OPTION;
  #  - FLUSH PRIVILEGES;
