{
 "title": "Padelquest",
 "description": "Dashboard set for Padelquest",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n  <br>\n  <h1>Welcome Back 👋 !</h1>\n  <h5>Padelquest Dashboard</h5>\n</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"caddy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "caddy_http_requests_total{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "MariaDB Status", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "Competitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "padelquest",
     "rawSql": "SELECT COUNT(id) FROM padelquest.competitions LIMIT 50 "
    }
   ]
  },
  {
   "title": "Players",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "padelquest",
     "rawSql": "SELECT COUNT(id) FROM padelquest.players LIMIT 50 "
    }
   ]
  },
  {
   "title": "Tournaments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "padelquest",
     "rawSql": "SELECT COUNT(id) FROM padelquest.tournaments LIMIT 50 "
    }
   ]
  },
  {
   "title": "Results",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "padelquest",
     "rawSql": "SELECT COUNT(id) FROM padelquest.tournaments_results LIMIT 50 "
    }
   ]
  },
  {
   "title": "HTTP(S) requests total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(caddy_http_requests_total{}[5m])*10)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP(S) requests in flight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(caddy_http_requests_in_flight{}[5m])*10)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<center>\nWith ❤️ by <a href=\"https://github.com/MarcOrfilaCarreras\">Marc Orfila Carreras</a>\n\n<br>\n\n<a href=\"https://github.com/MarcOrfilaCarreras/padelquest\">https://github.com/MarcOrfilaCarreras/padelquest</a>\n</center>"
   },
   "targets": [
    {
     "expr": "caddy_reverse_proxy_upstreams_healthy{}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}