name: Deploy

on:
  workflow_run:
      workflows: ["Build"]
      types:
        - completed

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      
      - name: Get new Docker Image
        run: docker pull marcorfilacarreras/padelquest
        
      - name: Stop API
        run: docker-compose -f docker-compose.yml down webapp
        
      - name: Start containers
        run: docker-compose -f docker-compose.yml up webapp
      
      - name: Remove old images
        run: docker image prune -f
